plugins {
    id 'java'
    id("xyz.jpenilla.run-paper") version "2.3.1"
    id("com.gradleup.shadow") version "9.0.0-rc3"
}

group = 'com.playerPlugin'
version = '1.0.0'

repositories {
    mavenCentral()
    maven {
        name = "spigotmc-repo"
        url = "https://hub.spigotmc.org/nexus/content/repositories/snapshots/"
    }
    maven { url 'https://jitpack.io' }
    maven {
        name = "tcoded-releases"
        url = "https://repo.tcoded.com/releases"
    }
}

dependencies {
    compileOnly("org.spigotmc:spigot-api:1.21.8-R0.1-SNAPSHOT")
    implementation("com.github.yvmouX:YLib:1.0.0-beta4")
    compileOnly 'org.xerial:sqlite-jdbc:3.42.0.0'
    compileOnly 'com.googlecode.json-simple:json-simple:1.1.1'
    implementation 'me.devnatan:inventory-framework-platform-paper:3.5.5'
    implementation('me.devnatan:inventory-framework-platform-bukkit:3.5.5')
    compileOnly "com.github.MilkBowl:VaultAPI:1.7"
}

tasks {
    runServer {
        // Configure the Minecraft version for our task.
        // This is the only required configuration besides applying the plugin.
        // Your plugin's jar (or shadowJar if present) will be used automatically.
        minecraftVersion("1.21")
        jvmArgs("-Dfile.encoding=UTF-8", "-Dsun.stdout.encoding=UTF-8", "-Dsun.stderr.encoding=UTF-8")
    }
}

shadowJar {
    relocate("cn.yvmou.ylib", "com.playerPlugin.playerTaskX.lib.ylib")

    relocate("me.devnatan.inventoryframework", "com.playerPlugin.playerTaskX.lib.inventoryframework")

    exclude { file ->
        // 匹配依赖中的 plugin.yml（根据其路径特征）
        file.name == 'plugin.yml' &&
                (file.path.contains('me/devnatan/inventoryframework') ||
                        file.path.contains('inventory-framework'))
    }

    // 确保只保留自己的 plugin.yml（双重保险）
    from('src/main/resources/plugin.yml') {
        into '/' // 强制放入根目录
    }

    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    archiveFileName = "${project.name}-${project.version}-all.jar"
}

def targetJavaVersion = 21
java {
    def javaVersion = JavaVersion.toVersion(targetJavaVersion)
    sourceCompatibility = javaVersion
    targetCompatibility = javaVersion
    if (JavaVersion.current() < javaVersion) {
        toolchain.languageVersion = JavaLanguageVersion.of(targetJavaVersion)
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'

    if (targetJavaVersion >= 10 || JavaVersion.current().isJava10Compatible()) {
        options.release.set(targetJavaVersion)
    }
}

processResources {
    def props = [version: version]
    inputs.properties props
    filteringCharset 'UTF-8'
    filesMatching('plugin.yml') {
        expand props
    }
}
